port=53
no-daemon
log-queries=extra
log-facility=/home/devl0rd/Github/AiBi-Server/logs/dnsmasq.log
listen-address=192.168.50.174,127.0.0.1
bind-interfaces
address=/api.aibipocket.com/192.168.50.174
server=1.1.1.1
